name: pull-request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.7.0
      
      - name: Install
        shell: bash 
        run: npm install

      - name: Build
        shell: bash 
        run: npm run build